language: go
go: '1.14'
script:
- make ci
after_success:
- make embed-assets
notifications:
  email: false
deploy:
- provider: script
  skip_cleanup: true
  script: bash scripts/goreleaser.sh
  on:
    tags: true
